### ISSUE TITLE
Stopping threshold bug?

### ISSUE THREAD

**Issue by LemonPi** [shahsohil/DCC#14]
The paper says we stop when change in assignment is below the stopping threshold, but the code implements this as:
```python
            if change_in_assign > stopping_threshold:
                flag += 1
            if flag == 4:
                break
```

This is a bug right? It should be `if change_in_assign < stopping_threshold:`
I'll fix this in my pull request if so.

**Comment by LemonPi** [comment]
Making the fix led to training for much more epochs with improvements on AMI and ACC. If the results in your paper was submitted with the same code with this bug in it, you might get better results with the fix!

![image](https://user-images.githubusercontent.com/5508542/55363046-d7e7a700-54a9-11e9-8eae-d82af74dd2aa.png)

**Comment by shahsohil** [comment]
> The paper says we stop when change in assignment is below the stopping threshold, but the code implements this as:
> 
> ```python
>             if change_in_assign > stopping_threshold:
>                 flag += 1
>             if flag == 4:
>                 break
> ```
> 
> This is a bug right? It should be `if change_in_assign < stopping_threshold:`
> I'll fix this in my pull request if so.

No. This isn't a bug. This was put in place to let DCC run until a point it breaks down the clustering. That is why flag is updated couple of times before algorithm is halted. The original criterion is little conservative.

I believe it was added after the paper was done. Overall, we found just minor change in AMI / ACC outputs.
