### ISSUE TITLE
Too many clusters after DCC

### ISSUE THREAD

**Issue by daihengming** [shahsohil/DCC#17]
Hey @shahsohil ，I'm trying to apply DCC to my own image dataset, and the results have too many clusters(1000 clusters for 3000 images), I'm wondering is there any way I can try to force the algorithm produce less clusters(for 5-10)? Could you please give me some suggestions？ Thanks.

**Comment by shahsohil** [comment]
Hi @daihengming,

Some checks:
1. The input data must be normalized. Refer make_data.py for the same. Also similar normalization must be applied for ceating underlying graph. Refer edge_construction.py code from RCC database. 
2. It still not resolved, then try increasing the 'k' for mkNN during the graph construction stage.

Based on outcome of above steps I will suggest others.
