### ISSUE TITLE
Error in (Running Deep Continuous Clustering) step

### ISSUE THREAD

**Issue by mz3220** [shahsohil/DCC#22]
Hello
Thank you very much for sharing your project

I am trying to re-implement it and as I go through this stage of the read.me file (Running Deep Continuous Clustering): I got the error below while running (DCCComputation.py file), Any advice?

**in computeHyperParams
  _sigma2 = float(3 * (epsilon[-1] ** 2))

builtins.IndexError: index -1 is out of bounds for axis 0 with size 0**

**Comment by shahsohil** [comment]
@mz3220 Thanks for pointing this out. I made a minor commit to overcome this issue.
