### ISSUE TITLE
Regarding error when running (DCC.py)

### ISSUE THREAD

**Issue by mz3220** [shahsohil/DCC#23]
**Hello

Thank you for this project

When running (DCC.py), I face the following run-time error:

builtins.IndexError: tensors used as indices must be long, byte or bool tensors

Can you help me with it.

**Comment by Xinzhi-Wang** [comment]
Hello,

I have a problem when run easy_example.py, it can't find the module named 'easydict'. Did you encounter this problem and how did you solve it？

ModuleNotFoundError: No module named 'easydict'

**Comment by wangxinzhi0** [comment]
Please have a try like this, convert Tensor to long
     
        # print(type(pairs),type(index)) # Tensor
        long_index = index.long()
        centroids = self.U[long_index]
