### ISSUE TITLE
download error

### ISSUE THREAD

**Issue by huweibo** [shahsohil/DCC#7]
$ git clone https://github.com/shahsohil/DCC.git
Cloning into 'DCC'...
remote: Enumerating objects: 76, done.
remote: Total 76 (delta 0), reused 0 (delta 0), pack-reused 76
Unpacking objects: 100% (76/76), done.
Downloading data/mnist/pretrained.mat (227 MB)
Error downloading object: data/mnist/pretrained.mat (bb0b757): Smudge error: Error downloading data/mnist/pretrained.mat (bb0b757ef4918b0f218c0e8b7d530c613ca60d5d1d0a81c1c1c33a34642fa057): batch response: This repository is over its data quota. Purchase more data packs to restore access.

Errors logged to R:\GitHub\DCC\.git\lfs\logs\20190225T132833.506642.log
Use `git lfs logs last` to view the log.
error: external filter 'git-lfs filter-process' failed
fatal: data/mnist/pretrained.mat: smudge filter lfs failed
warning: Clone succeeded, but checkout failed.
You can inspect what was checked out with 'git status'
and retry the checkout with 'git checkout -f HEAD'

Who knows how to solve this question?

**Comment by shahsohil** [comment]
Hi huweibo,

I am sorry for this confusion. I will share the data on google drive. Please find the link in README file.

**Comment by scottfleming** [comment]
Would it be possible to include the traindata.mat, testdata.mat, and pretrained.mat on that same google drive for sanity checking? Thanks so much for this great repo!

**Comment by shahsohil** [comment]
@scottfleming Same is included in the above mentioned link.
